version: "3.7"

services:
  reverse-proxy:
    build:
      context: ./
      dockerfile: Dockerfile-reverse-proxy
    image: reverse-proxy:custom
    container_name: proxy
    ports:
        - 80:80
        - 443:443
    restart: always

  db:
    container_name: db
    image: mariadb:10.4
    env_file:
      - environment/production.env
    volumes:
      - database_volume:/var/lib/mysql
      - scripts_volume:/docker-entrypoint-initdb.d
    # ports:
    #   - "3306:3306" # no need to have outsider access ? Or need I ?

  passbolt:
    container_name: passbolt
    image: passbolt/passbolt:latest
    tty: true
    depends_on:
      - db
      - reverse-proxy
    env_file:
      - environment/production.env
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "db:3306", "--", "/docker-entrypoint.sh"]
    # ports:
    #   - 80:80
    #   - 443:443
    restart: always

  standardnotes:
    container_name: notes
    image: arugifa/standardnotes-server
    depends_on:
      - db
      - reverse-proxy
    env_file:
      - environment/production.env
    command: >
      bash -c 'while ! nc -vz db 3306 ; do sleep 10 ; done &&
               sleep 2 &&
               /data/src/docker/entrypoint bootstrap &&
               /data/src/docker/entrypoint start'
    # ports:
    #   - 3000:3000
    restart: always

volumes:
  database_volume:
  gpg_volume:
  scripts_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/scripts/db