version: "3.7"

services:

  traefik:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-traefik
    image: traefik:custom
    container_name: traefik
    restart: unless-stopped
    volumes:
      - certificates:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - passwords_network
      - cloud_network
      - calendar_network
      - bookmarks_network
      - tasks_network
      - maps_network
      - cryptpad_network
      - mail_network
    ports:
      - "443:443"

  mysql:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-mysql
    image: mariadb:custom
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PASSBOLT_DATABASE=${PASSBOLT_DATABASE}
      - PASSBOLT_DB_USERNAME=${PASSBOLT_DB_USERNAME}
      - PASSBOLT_DB_PASSWORD=${PASSBOLT_DB_PASSWORD}
      - DAVIS_DATABASE=${DAVIS_DATABASE}
      - DAVIS_DB_USERNAME=${DAVIS_DB_USERNAME}
      - DAVIS_DB_PASSWORD=${DAVIS_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - database_mysql_volume:/var/lib/mysql
    networks:
      - passwords_network
      - calendar_network

  passbolt:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-passbolt
    image: passbolt:custom
    container_name: passbolt
    environment:
      - APP_FULL_BASE_URL=https://${PASSWORDS_DOMAIN}
      - DATASOURCES_DEFAULT_HOST=mysql
      - DATASOURCES_DEFAULT_DATABASE=${PASSBOLT_DATABASE}
      - DATASOURCES_DEFAULT_USERNAME=${PASSBOLT_DB_USERNAME}
      - DATASOURCES_DEFAULT_PASSWORD=${PASSBOLT_DB_PASSWORD}
      - EMAIL_DEFAULT_FROM=${EMAIL}
      - EMAIL_TRANSPORT_DEFAULT_HOST=${MAIL_HOST}
      - EMAIL_TRANSPORT_DEFAULT_PORT=${MAIL_PORT}
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=${MAIL_USERNAME}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${MAIL_PASSWORD}
      - PASSBOLT_PLUGINS_JWT_AUTHENTICATION_ENABLED=TRUE
      - PASSBOLT_PLUGINS_MOBILE_ENABLED=TRUE
    restart: unless-stopped
    command: ["/usr/bin/wait-for.sh", "mysql:3306", "--", "/docker-entrypoint.sh"]
    tty: true
    depends_on:
      - mysql
    volumes:
      - passbolt_gpg_volume:/etc/passbolt/gpg
      - passbolt_jwt_volume:/etc/passbolt/jwt
    networks:
      - passwords_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.passbolt.entrypoints=websecure"
      - "traefik.http.routers.passbolt.rule=Host(`${PASSWORDS_DOMAIN}`)"
      - "traefik.http.routers.passbolt.tls=true"
      - "traefik.http.routers.passbolt.tls.certresolver=default"
      - "traefik.http.routers.passbolt.middlewares=security@file"

  # Cozy Database
  couchdb:
    image: couchdb:2.3
    container_name: couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    restart: unless-stopped
    volumes:
      - database_couch_volume:/opt/couchdb/data
    networks:
      - cloud_network

  # Cozy Stack
  cozy:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-cozy
      args:
        version: "1.5.0"
    image: cozy:custom
    container_name: cozy
    environment:
      - DOMAIN=${CLOUD_DOMAIN}
      - COUCHDB_PROTOCOL=http
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COZY_ADMIN_PASSPHRASE=${COZY_ADMIN_PASSPHRASE}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DISABLE_TLS=false
      - MAIL_SKIP_CERTIFICATE_VALIDATION=false
    restart: unless-stopped
    depends_on:
      - couchdb
    volumes:
      - files_cozy_volume:/var/lib/cozy/data
    networks:
      - cloud_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cozy.entrypoints=websecure"
      - "traefik.http.routers.cozy.rule=Host(`${CLOUD_DOMAIN}`) || Host(`drive.${CLOUD_DOMAIN}`) || Host(`settings.${CLOUD_DOMAIN}`) || Host(`home.${CLOUD_DOMAIN}`)"
      - "traefik.http.routers.cozy.tls=true"
      - "traefik.http.routers.cozy.tls.certresolver=default"
      - "traefik.http.services.cozy.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.home-redirectregex.redirectregex.regex=^https://home.${CLOUD_DOMAIN}/?$$"
      - "traefik.http.middlewares.home-redirectregex.redirectregex.replacement=https://drive.${CLOUD_DOMAIN}"
      - "traefik.http.middlewares.home-redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.cozy-chain.chain.middlewares=home-redirectregex@docker,security@file"
      - "traefik.http.routers.cozy.middlewares=cozy-chain"

  # Caldav / Carddav / Webdav server
  davis-proxy:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-davis-proxy
    image: davis-proxy:custom
    container_name: davis-proxy
    restart: unless-stopped
    depends_on:
      - davis
    volumes:
      - davis_www:/var/www/davis
    networks:
      - calendar_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.davis.entrypoints=websecure"
      - "traefik.http.routers.davis.rule=Host(`${CALENDAR_DOMAIN}`)"
      - "traefik.http.routers.davis.tls=true"
      - "traefik.http.routers.davis.tls.certresolver=default"
      - "traefik.http.routers.davis.middlewares=security@file"

  davis:
    image: ghcr.io/tchapi/davis:v1.10.2
    container_name: davis
    environment:
      - APP_ENV=prod
      - APP_SECRET=${DAVIS_APP_SECRET}
      - DATABASE_URL=mysql://${DAVIS_DB_USERNAME}:${DAVIS_DB_PASSWORD}@mysql:3306/${DAVIS_DATABASE}
      - MAILER_DSN=smtp://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - ADMIN_LOGIN=${DAVIS_ADMIN_LOGIN}
      - ADMIN_PASSWORD=${DAVIS_ADMIN_PASSWORD}
      - AUTH_REALM=${DAVIS_AUTH_REALM}
      - AUTH_METHOD=Basic
      - IMAP_AUTH_URL=null
      - CALDAV_ENABLED=true
      - CARDDAV_ENABLED=true
      - WEBDAV_ENABLED=true
      - INVITE_FROM_ADDRESS=${EMAIL}
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - PUBLIC_DIR=/webdav
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - davis_www:/var/www/davis
      - files_webdav_volume:/webdav
    networks:
      - calendar_network

  # XBS = X-browser sync
  xbs:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-xbs
    image: xbs:custom
    container_name: xbs
    environment:
      - XBS_API_HOSTNAME=${BOOKMARKS_DOMAIN}
      - XBROWSERSYNC_DB_USER=${XBS_DB_USERNAME}
      - XBROWSERSYNC_DB_PWD=${XBS_DB_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - bookmarks_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xbs.entrypoints=websecure"
      - "traefik.http.routers.xbs.rule=Host(`${BOOKMARKS_DOMAIN}`)"
      - "traefik.http.routers.xbs.tls=true"
      - "traefik.http.routers.xbs.tls.certresolver=default"
      - "traefik.http.routers.xbs.middlewares=security@file"

  # XBS + Wekan database
  mongo:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-mongo
    image: mongo:custom
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - WEKAN_DATABASE=${WEKAN_DATABASE}
      - WEKAN_DB_USERNAME=${WEKAN_DB_USERNAME}
      - WEKAN_DB_PASSWORD=${WEKAN_DB_PASSWORD}
      - XBS_DATABASE=${XBS_DATABASE}
      - XBS_DB_USERNAME=${XBS_DB_USERNAME}
      - XBS_DB_PASSWORD=${XBS_DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - database_mongo_volume:/data/db
    networks:
      - bookmarks_network
      - tasks_network

  # Wekan (tasks)
  wekan:
    image: wekanteam/wekan
    container_name: tasks
    environment:
      - MONGO_URL=mongodb://${WEKAN_DB_USERNAME}:${WEKAN_DB_PASSWORD}@mongo:27017/${WEKAN_DATABASE}?authSource=admin
      - ROOT_URL=https://${TASKS_DOMAIN}
      - MAIL_URL=smtps://${MAIL_USERNAME}:${MAIL_PASSWORD}@${MAIL_HOST}:${MAIL_PORT}
      - MAIL_FROM=${WEKAN_MAIL_FROM}
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - tasks_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wekan.entrypoints=websecure"
      - "traefik.http.routers.wekan.rule=Host(`${TASKS_DOMAIN}`)"
      - "traefik.http.routers.wekan.tls=true"
      - "traefik.http.routers.wekan.tls.certresolver=default"
      - "traefik.http.routers.wekan.middlewares=security@file"

  # Mails (bound on a specific IP for the reverse to be unique)
  dovecot:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-dovecot
      args:
        mail_principal_user: ${MAIL_PRINCIPAL_USER}
        mail_principal_password: ${MAIL_PRINCIPAL_PASSWORD}
        mail_group_id: ${MAIL_VOLUME_GROUP}
    image: dovecot:custom
    container_name: mail-dovecot
    env_file: .env
    restart: unless-stopped
    volumes:
      - mails_volume:/var/mail
      - certificates:/etc/letsencrypt
    networks:
      - mail_network
    ports:
      - "${MAIL_HOST_IP}:143:143"
      - "${MAIL_HOST_IP}:993:993"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.reload_dovecot_for_certificates.schedule: "@weekly"
      ofelia.job-exec.reload_dovecot_for_certificates.command: "dovecot reload"

  smtpd:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-opensmtpd
      args:
        version: "v6.8.0p2"
        top_domain: ${TOP_DOMAIN}
        mail_domain: ${MAIL_DOMAIN}
        mail_principal_user: ${MAIL_PRINCIPAL_USER}
        mail_principal_password: ${MAIL_PRINCIPAL_PASSWORD}
        mail_no_reply_password: ${MAIL_NO_REPLY_PASSWORD}
        mail_group_id: ${MAIL_VOLUME_GROUP}
    image: opensmtpd:custom
    container_name: mail-smtpd
    env_file: .env
    restart: unless-stopped
    volumes:
      - mails_volume:/var/mail
      - certificates:/etc/letsencrypt
    networks:
      - mail_network
    ports:
      - "${MAIL_HOST_IP}:25:25"
      - "${MAIL_HOST_IP}:465:465"
      - "${MAIL_HOST_IP}:587:587"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.reload_smtpd_for_certificates.schedule: "@weekly"
      ofelia.job-exec.reload_smtpd_for_certificates.command: 'killall smtpd' # wait 60s max and then the container stops and restarts

  # This container :
  #  - exposes a traefik endpoint so that certificates for MAIL_DOMAIN are created and renewed by Traefik via labels
  # NB: Could be replaced by a webmail client
  mail-certificates-endpoint:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-mailendpoint
      args:
        mail_domain: ${MAIL_DOMAIN}
    image: httpd:custom
    container_name: mail-certificates-endpoint
    restart: unless-stopped
    networks:
      - mail_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.rule=Host(`${MAIL_DOMAIN}`)"
      - "traefik.http.routers.mail.tls=true"
      - "traefik.http.routers.mail.tls.certresolver=default"
      - "traefik.http.routers.mail.middlewares=security@file"

  # This container :
  #  - periodically exports the Traefik certificates to .pem files, in a shared volume
  #    so that dovecot and opensmtpd containers can consume them
  mail-certificates-dumper:
    image: ldez/traefik-certs-dumper:v2.7.4
    container_name: mail-certificates-dumper
    restart: unless-stopped
    entrypoint: sh -c '
      traefik-certs-dumper file --version v2
        --crt-name=fullchain --crt-ext=.pem
        --key-name=privkey --key-ext=.pem
        --domain-subdir
        --source /letsencrypt/acme.json --dest /letsencrypt/live/.
        --watch'
    volumes:
      - certificates:/letsencrypt

  # Cron scheduler - restarts dovecot and smtpd periodically so that new certificates are picked up correctly
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: mail-ofelia
    restart: unless-stopped
    depends_on:
      - smtpd
      - dovecot
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # kvtiles (Maps)
  maps:
    # See https://hub.docker.com/r/akhenakh/kvtiles/tags for available tags / zooms
    image: akhenakh/kvtiles:planet-10-latest
    container_name: maps
    restart: unless-stopped
    command: ["-tilesKey=${MAPS_API_KEY}"] # entrypoint is ["./kvtilesd"]
    networks:
      - maps_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maps.entrypoints=websecure"
      - "traefik.http.routers.maps.rule=Host(`${MAPS_DOMAIN}`)"
      - "traefik.http.routers.maps.tls=true"
      - "traefik.http.routers.maps.tls.certresolver=default"
      - "traefik.http.routers.maps.middlewares=security@file"
      - "traefik.http.services.maps.loadbalancer.server.port=8080"

  # Cryptpad (Documents)
  # See https://github.com/xwiki-labs/cryptpad
  cryptpad:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-cryptpad
      args:
        version: "4.12.1"
    image: cryptpad:custom
    container_name: cryptpad
    restart: unless-stopped
    volumes:
      - files_cryptpad_volume:/cryptpad/data
    networks:
      - cryptpad_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cryptpad.entrypoints=websecure"
      - "traefik.http.routers.cryptpad.rule=Host(`${CRYPTPAD_DOMAIN}`) || Host(`${CRYPTPAD_SANDBOX_DOMAIN}`)"
      - "traefik.http.routers.cryptpad.tls=true"
      - "traefik.http.routers.cryptpad.tls.certresolver=default"
      - "traefik.http.routers.cryptpad.middlewares=security@file"
      - "traefik.http.services.cryptpad.loadbalancer.server.port=3000"

networks:
  passwords_network: ~
  cloud_network: ~
  calendar_network: ~
  bookmarks_network: ~
  tasks_network: ~
  # We force the subnet here, so we can use it in
  # the iptables routing command afterwards to make
  # the outgoing packets go through a specific IP.
  # See https://stackoverflow.com/a/46493740/1741150
  mail_network:
    ipam:
      config:
        - subnet: "172.100.0.0/16"
  maps_network: ~
  cryptpad_network: ~

volumes:
  certificates:
    name: certificates
  davis_www:
    name: davis_www 
  # These volumes are actually attached OpenStack Block storage
  passbolt_gpg_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/files/passbolt/gpg
  passbolt_jwt_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/files/passbolt/jwt
  database_mysql_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/databases/mysql
  database_couch_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/databases/couch
  database_mongo_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/databases/mongo
  files_cozy_volume: # It stores the cozy files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/files/cozy
  files_cryptpad_volume: # It stores the cryptpad data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/files/cryptpad
  mails_volume: # It stores the mail data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/files/mails
  files_webdav_volume: # It stores the webdav data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/files/webdav
