version: "3.7"

services:

  traefik:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-traefik
    image: traefik:custom
    container_name: traefik
    restart: unless-stopped
    volumes:
      - certificates:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - directus_network
      - navidrome_network
      - flatnotes_network
      - filebrowser_network
    ports:
      - "443:443"

  database:
    image: postgis/postgis:13-master
    volumes:
      - directus-data:/var/lib/postgresql/data
    networks:
      - directus_network
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

  cache:
    image: redis:6
    networks:
      - directus_network

  filebrowser:
    image: filebrowser/filebrowser
    networks:
      - filebrowser_network
    volumes:
      - ./navidrome/music:/srv/music
      - ./photos:/srv/photos
    ports:
      - 8888:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.rule=Host(`dir.narah.app`)"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=default"
      - "traefik.http.routers.filebrowser.middlewares=security@file"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - directus-uploads:/directus/uploads
      - ./directus/modules:/directus/extensions/modules
    networks:
      - directus_network
    depends_on:
      - cache
      - database
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: '${POSTGRES_DB}'
      DB_USER: '${POSTGRES_USER}'
      DB_PASSWORD: '${POSTGRES_PASSWORD}'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: '${DIRECTUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DIRECTUS_ADMIN_PWD}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=default"
      - "traefik.http.routers.api.middlewares=security@file"
      - "traefik.http.services.api.loadbalancer.server.port=8055"

  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    networks:
      - navidrome_network
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
      ND_UILOGINBACKGROUNDURL: ''
      ND_ENABLEGRAVATAR: true
      ND_UIWELCOMEMESSAGE: 'va voir 3ami brahim'
    volumes:
      - ./navidrome/data:/data
      - ./navidrome/music:/music:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music.entrypoints=websecure"
      - "traefik.http.routers.music.rule=Host(`${MUSIC_DOMAIN}`)"
      - "traefik.http.routers.music.tls=true"
      - "traefik.http.routers.music.tls.certresolver=default"
      - "traefik.http.routers.music.middlewares=security@file"
      - "traefik.http.services.music.loadbalancer.server.port=4533"

  flatnotes:
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "ami"
      FLATNOTES_PASSWORD: ${FLATNOTES_PASSWORD}
      FLATNOTES_SECRET_KEY: ${FLATNOTES_SECRET_KEY}
    volumes:
      - "./flatnotes:/data"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - flatnotes_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flatnotes.entrypoints=websecure"
      - "traefik.http.routers.flatnotes.rule=Host(`${FLATNOTES_DOMAIN}`)"
      - "traefik.http.routers.flatnotes.tls=true"
      - "traefik.http.routers.flatnotes.tls.certresolver=default"
      - "traefik.http.routers.flatnotes.middlewares=security@file"
      - "traefik.http.services.flatnotes.loadbalancer.server.port=8080"

networks:
  directus_network: ~
  navidrome_network: ~
  filebrowser_network: ~
  flatnotes_network: ~


volumes:
  certificates:
    name: certificates
  directus-data:
  photoview_cache:
  directus-uploads:
  files_webdav_volume:
  database_mysql_volume:
