version: "3.7"

services:

  traefik:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-traefik
    image: traefik:custom
    container_name: traefik
    restart: unless-stopped
    volumes:
      - certificates:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cryptpad_network
    ports:
      - "443:443"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.api.rule=Host(`${STATUS_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=default"
      # - "traefik.http.middlewares.auth.basicauth.users=${STATUS_CREDENTIALS}"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.middlewares=security@file"

  cryptpad:
    build:
      context: ./
      dockerfile: ./build/Dockerfile-cryptpad
      args:
        version: "5.2.1"
    image: cryptpad:custom
    container_name: cryptpad
    restart: unless-stopped
    volumes:
      - files_cryptpad_volume:/cryptpad/data
    networks:
      - cryptpad_network
    labels:
      - "traefik.enable=true"
      # See https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf
      # First case (secure)
      - "traefik.http.routers.cryptpad-safe.entrypoints=websecure"
      - "traefik.http.routers.cryptpad-safe.rule=(Host(`pad.narah.io`) && !PathPrefix(`/unsafeiframe/inner.html`)) || (Host(`sb.narah.io`) && !Path(`/{t:(sheet|doc|presentation)}/inner.html{n:.*}`, `/common/onlyoffice/{n:.*}/{m:.*}.html{r:.*}`))"
      - "traefik.http.routers.cryptpad-safe.tls=true"
      - "traefik.http.routers.cryptpad-safe.tls.certresolver=default"
      - "traefik.http.services.cryptpad-safe.loadbalancer.server.port=3000"
      - "traefik.http.routers.cryptpad-safe.service=cryptpad-safe"
      - "traefik.http.middlewares.custom.headers.accessControlAllowOriginList=sb.narah.io"
      - "traefik.http.middlewares.custom.headers.contentSecurityPolicy=default-src 'none'; child-src https://pad.narah.io; worker-src 'self'; media-src blob:; style-src 'unsafe-inline' 'self' https://pad.narah.io; script-src 'self' resource: https://pad.narah.io; connect-src 'self' https://pad.narah.io blob: wss://pad.narah.io https://sb.narah.io; font-src 'self' data: https://pad.narah.io; img-src 'self' data: blob: https://pad.narah.io; frame-src 'self' https://sb.narah.io blob:; frame-ancestors 'self' https://pad.narah.io"
      - "traefik.http.middlewares.cryptpad-safe-chain.chain.middlewares=custom,cryptpad@file,security@file"
      - "traefik.http.routers.cryptpad-safe.middlewares=cryptpad-safe-chain"
      # Second case (unsafe)
      - "traefik.http.routers.cryptpad-unsafe.entrypoints=websecure"
      - "traefik.http.routers.cryptpad-unsafe.rule=(Host(`pad.narah.io`) && PathPrefix(`/unsafeiframe/inner.html`)) || (Host(`sb.narah.io`) && Path(`/{t:(sheet|doc|presentation)}/inner.html{n:.*}`, `/common/onlyoffice/{n:.*}/{m:.*}.html{r:.*}`))"
      - "traefik.http.routers.cryptpad-unsafe.tls=true"
      - "traefik.http.routers.cryptpad-unsafe.tls.certresolver=default"
      - "traefik.http.services.cryptpad-unsafe.loadbalancer.server.port=3000"
      - "traefik.http.routers.cryptpad-unsafe.service=cryptpad-unsafe"
      - "traefik.http.middlewares.custom2.headers.accessControlAllowOriginList=sb.narah.io"
      - "traefik.http.middlewares.custom2.headers.contentSecurityPolicy=default-src 'none'; child-src https://pad.narah.io; worker-src 'self'; media-src blob:; style-src 'unsafe-inline' 'self' https://pad.narah.io; script-src 'self' 'unsafe-eval' 'unsafe-inline' resource: https://pad.narah.io; connect-src 'self' https://pad.narah.io blob: wss://pad.narah.io https://sb.narah.io; font-src 'self' data: https://pad.narah.io; img-src 'self' data: blob: https://pad.narah.io; frame-src 'self' https://sb.narah.io blob:; frame-ancestors 'self' https://pad.narah.io"
      - "traefik.http.middlewares.cryptpad-unsafe-chain.chain.middlewares=custom2,cryptpad@file,security@file"
      - "traefik.http.routers.cryptpad-unsafe.middlewares=cryptpad-unsafe-chain"

networks:
  cryptpad_network: ~

volumes:
  certificates:
    name: certificates
  files_cryptpad_volume:
