[http.middlewares]
  [http.middlewares.security.headers]
    stsSeconds = 31536000
    sslRedirect = true
  [http.middlewares.cors.headers]
    [http.middlewares.cors.headers.customResponseHeaders]
      Cross-Origin-Resource-Policy = "cross-origin"
      Cross-Origin-Embedder-Policy = "require-corp"

[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
      # sniStrict = true
