#!/bin/bash

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<- EOSQL

      -- Davis
      CREATE DATABASE IF NOT EXISTS \`${DAVIS_DATABASE}\`;
      CREATE USER IF NOT EXISTS '${DAVIS_DB_USERNAME}'@'%' IDENTIFIED BY '${DAVIS_DB_PASSWORD}';
      GRANT ALL ON \`${DAVIS_DATABASE}\`.* TO '${DAVIS_DB_USERNAME}'@'%';


EOSQL
